module.exports = {
    corePlugins: {
        container: false,
    },
    purge: ['./components/**/*.js', './pages/**/*.js'],
    theme: {
        fontSize: {
            xs: ['.75rem', '1.5rem'],
            sm: ['.875rem', '1.5rem'],
            baseMobile: ['1rem', '1.5rem'],
            base: ['1.2rem', '1.75rem'],
            lg: ['1.5rem', '2.25rem'],
            lgr: ['1.75rem', '3rem'],
            xl: ['2.5rem', '4rem'],
            xxl: ['3.4375rem', '4rem'],
        },
        colors: {
            blue: '#114B5F',
            middleblue: '#4695BC',
            lightblue: '#F2F9FD',
            indigoblue: '#0D3B66',
            green: '#1A936F',
            red: '#D1495B',
            winered: '#702632',
            pink: '#FFA5AB',
            yellow: '#EDAE49',
            gray: '#E5E5E5',
            white: '#FFFFFF',
            lightbrown: '#F3E9D2',
            lightgray: '#CCE6F6',
            darkgray: '#515A5E',
            black: '#000000',
            transparent: 'transparent',
            rating0: '#E5E5E5',
            rating1: '#D00000',
            rating2: '#DC2F02',
            rating3: '#E85D04',
            rating4: '#F48C06',
            rating5: '#FAA307',
            rating6: '#FFBA08',
            rating7: '#FFE33F',
            rating8: '#A4E24D',
            rating9: '#7BC423',
            rating10: '#18920D',
        },
        extend: {},
    },
    variants: {},
    plugins: [require('tailwind-bootstrap-grid')({
        gridGutterWidth: '20px'
    })],
}